name: talos
services:
  store:
    type: compose
    volumes:
      agdata:
      agconfig:
    run:
      - agtool repos create http://minos:password@127.0.0.1:10035/repositories/talos
      - agtool repos create http://minos:password@127.0.0.1:10035/repositories/tests
    services:
      image: franzinc/agraph:v7.2.0
      command: /entrypoint.sh
      environment:
        AGRAPH_SUPER_USER: minos
        AGRAPH_SUPER_PASSWORD: password
        ENABLE_DATA_WRITE: "true"
        ENABLE_UPDATE: "true"
        ENABLE_UPLOAD: "true"
      tmpfs:
        - /dev/shm
      volumes:
        - agdata:/agraph/data
        - agconfig:/agraph/etc

tooling:
  agtool:
    service: store
    cmd: agtool

proxy:
  store:
    - db.talos.lndo.site:10035
